### ISSUE TITLE
Quality of Images

### ISSUE THREAD

**Issue by Nethmee** [bitsoferised/ShareABook_Backend#104]
The quality of the compressed images is unpredictable..therefore it often gives images with very low quality.

**Comment by dilinipeirs** [comment]
to be handled from backend issue #109

**Comment by dilinipeirs** [comment]
cloudinary integration seems to be time consuming at the moment. Therefore as per the discussion with @Nethmee the images will be hosted in Amazon S3. The quality of the images will not be reduced now. (the image compression algorithm is not being used and it has been commented.)

The calculation of storing images is as follows.

- Maximum size of 1 book image - 2MB (this is limited by the frontend itself upon uploading)

- storage we are getting from Amazon S3 ->  5GB = 1024x5  = 5120MB

- total no. of images (2MB sized ->worst case) that can be stored = 5120/2 = 2560 images

- for 1 book -> we are letting the user upload 3 images.

- Therefore the number of books that can be uploaded with 3 images would be = 2560/3 = 853 books (this is the worst case)

**For our first 6 months, this storage would be enough for storing images of books.**

**Comment by dilinipeirs** [comment]
the image viewing error due to the error in the compression algo has been adjusted manually.. Therefore @Nethmee please check frontend issues #66 and #62
