### ISSUE TITLE
create email preferences and implement

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Backend#115]
I think it is better we have send promotional emails from the start itself. I see this is a days work and can be accomplished.

Therefore in order to do this, i need to know, what are the types of promotional emails that needs to be sent and have a list of email preferences that user can manage. Therefore, please research on this and give me a doc (preferrably a list of instances to let the user subscribe and unsubscribe from).

You can see the emails that are currently being sent from the system by logging into shareabook.customercare@gmail.com

**Comment by dilinipeirs** [comment]
as for the research part, @RashmiChrystal or @Nethmee please self assign yourself if you think can research on it. one person is enough.

@Nethmi96 we can add this email preferences part in the user's account settings.. sorry i remembered this now only.. do you think its too much work for you?
i can implement all the endpoints, you have to create a page to manage email settings

**Comment by dilinipeirs** [comment]
We can also implement another part to let the admin filter out the email addresses according to the ppl who have subscribed for promotional emails..

endpoints can be made..
- to get book seekers who've subscribed for promotional emails
- to get book donating ppl who've subscribed for promotional emails
etc.

But if this is too much work for now, we can skip this admin mail list retrieving part to later.. as it is not directly affecting the users.

@Nethmi96 please comment your ideas on this too

**Comment by Nethmee** [comment]
> I think it is better we have send promotional emails from the start itself. I see this is a days work and can be accomplished.
> 
> Therefore in order to do this, i need to know, what are the types of promotional emails that needs to be sent and have a list of email preferences that user can manage. Therefore, please research on this and give me a doc (preferrably a list of instances to let the user subscribe and unsubscribe from).
> 
> You can see the emails that are currently being sent from the system by logging into [shareabook.customercare@gmail.com](mailto:shareabook.customercare@gmail.com)

What do you have in mind as promotions?

**Comment by Nethmee** [comment]
> > I think it is better we have send promotional emails from the start itself. I see this is a days work and can be accomplished.
> > Therefore in order to do this, i need to know, what are the types of promotional emails that needs to be sent and have a list of email preferences that user can manage. Therefore, please research on this and give me a doc (preferrably a list of instances to let the user subscribe and unsubscribe from).
> > You can see the emails that are currently being sent from the system by logging into [shareabook.customercare@gmail.com](mailto:shareabook.customercare@gmail.com)
> 
> What do you have in mind as promotions?

**Comment by Nethmi96** [comment]
> as for the research part, @RashmiChrystal or @Nethmee please self assign yourself if you think can research on it. one person is enough.
> 
> @Nethmi96 we can add this email preferences part in the user's account settings.. sorry i remembered this now only.. do you think its too much work for you?
> i can implement all the endpoints, you have to create a page to manage email settings

What do I really have to do here? Can you please give me a please explanation cz I kind of have no idea on what this is about 🙉

**Comment by dilinipeirs** [comment]
> > I think it is better we have send promotional emails from the start itself. I see this is a days work and can be accomplished.
> > Therefore in order to do this, i need to know, what are the types of promotional emails that needs to be sent and have a list of email preferences that user can manage. Therefore, please research on this and give me a doc (preferrably a list of instances to let the user subscribe and unsubscribe from).
> > You can see the emails that are currently being sent from the system by logging into [shareabook.customercare@gmail.com](mailto:shareabook.customercare@gmail.com)
> 
> What do you have in mind as promotions?

To send emails about products to book seekers..
To send emails to ppl who sell books saying there are book seekers from these areas..

likewise

**Comment by dilinipeirs** [comment]
> > as for the research part, @RashmiChrystal or @Nethmee please self assign yourself if you think can research on it. one person is enough.
> > @Nethmi96 we can add this email preferences part in the user's account settings.. sorry i remembered this now only.. do you think its too much work for you?
> > i can implement all the endpoints, you have to create a page to manage email settings
> 
> What do I really have to do here? Can you please give me a please explanation cz I kind of have no idea on what this is about 🙉

have u seen email preferences page on other sites, where you are directed when u click on 'Unsubscribe' link in a promotional email? that kind of a page will have to be made if we are gonna implement this

**Comment by dilinipeirs** [comment]
With the limited time frame available and workload of the team members, decided to pause this task until the post-release phase of the product.
