### ISSUE TITLE
User Notifications

### ISSUE THREAD

**Issue by Nethmee** [bitsoferised/ShareABook_Backend#121]
![user notifications -new user](https://user-images.githubusercontent.com/40081010/83878101-3d43c180-a759-11ea-8c47-afbba1df3487.PNG)
throws an error (status code:5000) when a new user's email is entered.
(new user : a user who doesn't have any notifications)

**Comment by dilinipeirs** [comment]
there was a bug in this.. and it is fixed now

**Comment by dilinipeirs** [comment]
the API doc was updated to get notifications for admins. please refer the doc
