### ISSUE TITLE
User registration -email verification

### ISSUE THREAD

**Issue by Nethmee** [bitsoferised/ShareABook_Backend#123]
![email verification error 2](https://user-images.githubusercontent.com/40081010/83906566-7001b000-a781-11ea-8b5d-04f48fd7d043.PNG)
throws an error as follows.
![email verificaiton error-1](https://user-images.githubusercontent.com/40081010/83906587-7abc4500-a781-11ea-959c-42833a3cdd94.PNG)

**Comment by dilinipeirs** [comment]
this is a mistake by our QA lead 😜😜

no issue in the backend
