### ISSUE TITLE
book weight to be calculated before sending to the delivery agent's API

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Backend#142]
get the specs from @Nethmee about how to do the calculation

**Comment by dilinipeirs** [comment]
https://docs.google.com/document/d/18DV7yZ6iMztWmEyR6dHFjTwiZnfhOCQmofUWTUWo4KI/edit?usp=sharing

**Comment by dilinipeirs** [comment]
@Nethmee -Dilini call summary:
1. nethmee is to revise the material types in the frontend and give a feasible list of material types for each product type (where necesary)
2. nethmee is to indicate all the assumptions she made while doing the calculations. (considering book covers for weight calculations)
3. logic needs to indicate no. of pages/2 when calculating the weight when necessary

please provide a detailed doc in order for the logic to be developed in the backend. Thanks.

*After sample weights has been calculated, @Nethmee is to talk to the delivery ppl regarding whether these weight estimations are OK or not. and change if necessary.*

*Also talk to delivery ppl regarding any agreement to be made.. or to have something in written as proof.. At least an email chain regarding the official work*

**Comment by dilinipeirs** [comment]
@Nethmee this is the current category distribution

![IMG-20200814-WA0001.jpeg](https://user-images.githubusercontent.com/28673959/90211284-e409a580-de0d-11ea-9a43-a191cb4b4163.jpeg)

Please upload the category materials list after you finalize them. Thanks

**Comment by dilinipeirs** [comment]
@Nethmee this is the current category distribution

![IMG-20200814-WA0001.jpeg](https://user-images.githubusercontent.com/28673959/90211284-e409a580-de0d-11ea-9a43-a191cb4b4163.jpeg)

Please upload the category materials list after you finalize them. Thanks

**Comment by Nethmee** [comment]
sure I'll upload it ASAP

**Comment by dilinipeirs** [comment]
book approx weight calculation is done upon adding the book to the system
