### ISSUE TITLE
New field in user data table

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Backend#160]
Add a new field in user data table as District and do the filtration in "Books which are nearest to you" according to that.

**Comment by dilinipeirs** [comment]
this is made
check Swagger for the endpoint.
the city endpoint is still there. i did not remove it in case needed in future. have made a new endpoint for district but currently it returns an empty list.

looking into it.

@Nethmi96 u can meantime integrate the new endpoint

**Comment by dilinipeirs** [comment]
this is completed
