### ISSUE TITLE
Notification support in backend

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Backend#72]
steps are here
https://firebase.google.com/docs/cloud-messaging/server#firebase-admin-sdk-for-fcm

**Comment by dilinipeirs** [comment]
according to frontend issue #22 firebase will not be used..
manual implementations will be carried out

**Comment by dilinipeirs** [comment]
manual implementations completed. 
not tested. @Nethmee will carry out the testing

**Comment by Nethmee** [comment]
> manual implementations completed.
> not tested. @Nethmee will carry out the testing

Okayy I will  do it ASAP.
