### ISSUE TITLE
books according to the book location

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Backend#78]
this feature can be added in the future

**Comment by dilinipeirs** [comment]
@Nethmi96 We talked about this once i remember.. Can you give your ideas on this?

I think you suggested this to be added to the advanced search?

**Comment by dilinipeirs** [comment]
@Nethmi96 we can have this as another list of trending topics right?
please give your ideas on this

**Comment by dilinipeirs** [comment]
> @Nethmi96 We talked about this once i remember.. Can you give your ideas on this?
> 
> I think you suggested this to be added to the advanced search?

this comment is to be disregarded

**Comment by Nethmi96** [comment]
> @Nethmi96 we can have this as another list of trending topics right?
> 
> we can show the books that is in the same city as the user..
> 
> please give your ideas on this

yeah that seems good!

**Comment by dilinipeirs** [comment]
@Nethmi96 this is completed.
please refer the documentation/swagger to know more details
